path: 'E:/Oslo/OsloMet/Fourth semester/DetectionOfBallotPaper/modules/yolodata/set4'
train: train_set/images/train
val: val_set/images/train

nc: 44  # Number of classes

names: [
  "balance",
  "bus",
  "candle_light",
  "computer",
  "conch",
  "cycle",
  "damphu",
  "dog",
  "farmer",
  "hammer_scythe",
  "hand_palm",
  "heart",
  "hoe",
  "house",
  "invalid_stamp",
  "key",
  "ladder",
  "lock",
  "lotus",
  "loud_speaker",
  "mother_and_child",
  "namaste",
  "nepali_big_basket",
  "nepali_cap",
  "nepali_jug",
  "nepali_madal",
  "nepali_small_basket",
  "owl",
  "pen",
  "roaster",
  "sheep",  
  "star",
  "stick",
  "sun",
  "tiger",
  "torch_light",
  "tree",
  "turtle",
  "umbrella",
  "valid_stamp",
  "water_glass",
  "water_jug",
  "woman_man",
  "wooden_wheel"
]